networks:
  default:
    name: mynetwork
    driver: bridge
    
services:
  cf.access-proxy:
    image: cf.access-proxy
    ports:
      - "15141:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    build:
      context: .
      dockerfile: CF.AccessProxy/Dockerfile
